//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ImageCrop.Models
{
    #region 內容
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    public partial class ImageCropEntities : ObjectContext
    {
        #region 建構函式
    
        /// <summary>
        /// 使用在應用程式組態檔的 'ImageCropEntities' 區段中找到的連接字串，初始化新的 ImageCropEntities 物件。
        /// </summary>
        public ImageCropEntities() : base("name=ImageCropEntities", "ImageCropEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ImageCropEntities 物件。
        /// </summary>
        public ImageCropEntities(string connectionString) : base(connectionString, "ImageCropEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ImageCropEntities 物件。
        /// </summary>
        public ImageCropEntities(EntityConnection connection) : base(connection, "ImageCropEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 部分方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<UploadImage> UploadImage
        {
            get
            {
                if ((_UploadImage == null))
                {
                    _UploadImage = base.CreateObjectSet<UploadImage>("UploadImage");
                }
                return _UploadImage;
            }
        }
        private ObjectSet<UploadImage> _UploadImage;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<UploadImage2> UploadImage2
        {
            get
            {
                if ((_UploadImage2 == null))
                {
                    _UploadImage2 = base.CreateObjectSet<UploadImage2>("UploadImage2");
                }
                return _UploadImage2;
            }
        }
        private ObjectSet<UploadImage2> _UploadImage2;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 將新物件加入 UploadImage EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddToUploadImage(UploadImage uploadImage)
        {
            base.AddObject("UploadImage", uploadImage);
        }
    
        /// <summary>
        /// 將新物件加入 UploadImage2 EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddToUploadImage2(UploadImage2 uploadImage2)
        {
            base.AddObject("UploadImage2", uploadImage2);
        }

        #endregion
    }
    

    #endregion
    
    #region 實體
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ImageCropModel", Name="UploadImage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UploadImage : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 UploadImage 物件。
        /// </summary>
        /// <param name="id">ID 屬性的初始值。</param>
        /// <param name="originalImage">OriginalImage 屬性的初始值。</param>
        /// <param name="createDate">CreateDate 屬性的初始值。</param>
        public static UploadImage CreateUploadImage(global::System.Guid id, global::System.String originalImage, global::System.DateTime createDate)
        {
            UploadImage uploadImage = new UploadImage();
            uploadImage.ID = id;
            uploadImage.OriginalImage = originalImage;
            uploadImage.CreateDate = createDate;
            return uploadImage;
        }

        #endregion
        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OriginalImage
        {
            get
            {
                return _OriginalImage;
            }
            set
            {
                OnOriginalImageChanging(value);
                ReportPropertyChanging("OriginalImage");
                _OriginalImage = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OriginalImage");
                OnOriginalImageChanged();
            }
        }
        private global::System.String _OriginalImage;
        partial void OnOriginalImageChanging(global::System.String value);
        partial void OnOriginalImageChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CropImage
        {
            get
            {
                return _CropImage;
            }
            set
            {
                OnCropImageChanging(value);
                ReportPropertyChanging("CropImage");
                _CropImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CropImage");
                OnCropImageChanged();
            }
        }
        private global::System.String _CropImage;
        partial void OnCropImageChanging(global::System.String value);
        partial void OnCropImageChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdateDate
        {
            get
            {
                return _UpdateDate;
            }
            set
            {
                OnUpdateDateChanging(value);
                ReportPropertyChanging("UpdateDate");
                _UpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateDate");
                OnUpdateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdateDate;
        partial void OnUpdateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdateDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ImageCropModel", Name="UploadImage2")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UploadImage2 : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 UploadImage2 物件。
        /// </summary>
        /// <param name="id">ID 屬性的初始值。</param>
        /// <param name="originalImage">OriginalImage 屬性的初始值。</param>
        /// <param name="createDate">CreateDate 屬性的初始值。</param>
        /// <param name="updateDate">UpdateDate 屬性的初始值。</param>
        public static UploadImage2 CreateUploadImage2(global::System.Guid id, global::System.String originalImage, global::System.DateTime createDate, global::System.DateTime updateDate)
        {
            UploadImage2 uploadImage2 = new UploadImage2();
            uploadImage2.ID = id;
            uploadImage2.OriginalImage = originalImage;
            uploadImage2.CreateDate = createDate;
            uploadImage2.UpdateDate = updateDate;
            return uploadImage2;
        }

        #endregion
        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OriginalImage
        {
            get
            {
                return _OriginalImage;
            }
            set
            {
                OnOriginalImageChanging(value);
                ReportPropertyChanging("OriginalImage");
                _OriginalImage = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OriginalImage");
                OnOriginalImageChanged();
            }
        }
        private global::System.String _OriginalImage;
        partial void OnOriginalImageChanging(global::System.String value);
        partial void OnOriginalImageChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CropImage
        {
            get
            {
                return _CropImage;
            }
            set
            {
                OnCropImageChanging(value);
                ReportPropertyChanging("CropImage");
                _CropImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CropImage");
                OnCropImageChanged();
            }
        }
        private global::System.String _CropImage;
        partial void OnCropImageChanging(global::System.String value);
        partial void OnCropImageChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SelectionX1
        {
            get
            {
                return _SelectionX1;
            }
            set
            {
                OnSelectionX1Changing(value);
                ReportPropertyChanging("SelectionX1");
                _SelectionX1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SelectionX1");
                OnSelectionX1Changed();
            }
        }
        private Nullable<global::System.Int32> _SelectionX1;
        partial void OnSelectionX1Changing(Nullable<global::System.Int32> value);
        partial void OnSelectionX1Changed();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SelectionX2
        {
            get
            {
                return _SelectionX2;
            }
            set
            {
                OnSelectionX2Changing(value);
                ReportPropertyChanging("SelectionX2");
                _SelectionX2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SelectionX2");
                OnSelectionX2Changed();
            }
        }
        private Nullable<global::System.Int32> _SelectionX2;
        partial void OnSelectionX2Changing(Nullable<global::System.Int32> value);
        partial void OnSelectionX2Changed();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SelectionY1
        {
            get
            {
                return _SelectionY1;
            }
            set
            {
                OnSelectionY1Changing(value);
                ReportPropertyChanging("SelectionY1");
                _SelectionY1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SelectionY1");
                OnSelectionY1Changed();
            }
        }
        private Nullable<global::System.Int32> _SelectionY1;
        partial void OnSelectionY1Changing(Nullable<global::System.Int32> value);
        partial void OnSelectionY1Changed();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SelectionY2
        {
            get
            {
                return _SelectionY2;
            }
            set
            {
                OnSelectionY2Changing(value);
                ReportPropertyChanging("SelectionY2");
                _SelectionY2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SelectionY2");
                OnSelectionY2Changed();
            }
        }
        private Nullable<global::System.Int32> _SelectionY2;
        partial void OnSelectionY2Changing(Nullable<global::System.Int32> value);
        partial void OnSelectionY2Changed();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UpdateDate
        {
            get
            {
                return _UpdateDate;
            }
            set
            {
                OnUpdateDateChanging(value);
                ReportPropertyChanging("UpdateDate");
                _UpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateDate");
                OnUpdateDateChanged();
            }
        }
        private global::System.DateTime _UpdateDate;
        partial void OnUpdateDateChanging(global::System.DateTime value);
        partial void OnUpdateDateChanged();

        #endregion
    
    }

    #endregion
    
}
